### ISSUE TITLE
Performance drops when working with large item quantities

### ISSUE THREAD

**Issue by ShadowNekoG** [Infinitay/essence-pouch-degrading#35]
When i have the plugin on if i take coins out of my bank or the ge the game will freeze for multiple seconds.

**Comment by Infinitay** [comment]
I never noticed this throughout all my testing. Thanks for bringing it to my attention. It happened to me as well when I took out any large amount (about a mill) of an item. Sorry for the inconvenience but until I can push a fix you should disable the plugin until you want to use the plugin's features. I'd recommend banking your coins in your inventory in that case too, or don't bring too many with you.

**Comment by PetGirlBecky** [comment]
When i withdraw coins, I get a 10 second freeze ingame

**Comment by Infinitay** [comment]
> When i withdraw coins, I get a 10 second freeze ingame

Yea I'm sorry about this. I have fixed it in #35 but didn't merge it yet because I wanted to test it in-game; however, I can't play to test it ATM.

I am hoping to push the fix out later today along with several other changes since the release of the plugin. I have one last issue to fix #30 and I will submit the plugin update request to the Plugin Hub.

I'm sorry for the troubles. Currently, I recommend disabling the plugin when you're not runecrafting. When you are runecrafting, try to avoid taking out large amount of GP multiple times. Again, sorry for the annoying issue but the fix will be  pushed soon hopefully.

**Comment by Infinitay** [comment]
@ShadowNekoG @PetGirlBecky Sorry for the delay in pushing out a fix as I kept piling on additional fixes or features as I came across them. I finally pushed the changes to the RL Plugin Hub so hopefully it'll be reviewed and accepted soon when the maintainers have free time.

You can track the status here: https://github.com/runelite/plugin-hub/pull/6925

Thank you both bringing up the issue to my attention, and I apologize for any inconvenience or issues you faced as a result of this bug.
