### ISSUE TITLE
Cannot disable decay stat only

### ISSUE THREAD

**Issue by dillasyx** [Infinitay/essence-pouch-degrading#58]
No matter which option in the settings I deactivate, both number are hidden..

**Comment by Infinitay** [comment]
I fixed the issue a week ago (https://github.com/Infinitay/essence-pouch-tracker/commit/f66f241eb12359e39f4b840b96220c145bcc0442) but I never submitted the update to the plugin hub because at the time I was working on adding further support for the degraded colossal pouch and degraded pouches in general. However, I got side-tracked and didn't finish implementing a proper solution or testing to it, so I never pushed the update. I'll go ahead and push the changes for the pouch overlay now. Sorry about that.

**Comment by Infinitay** [comment]
Pushed the changes to the plugin hub and it's currently waiting for one more approval and merge: https://github.com/runelite/plugin-hub/pull/7081
